### PR TITLE
Next visit

### PR DESCRIPTION
**Pull request by earlAchromatic**

### CODE REVIEW

**Comment by earlAchromatic** [comment]
@Hyperion-Web/core

**Comment by earlAchromatic** [comment]
@hyperion-web

**Comment by earlAchromatic** [comment]
@Hyperion-Web

**Review by oscl8tr — APPROVED** [review]
> Reviewed 117 of 117 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/Hyperion-Web/Nebula/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 39 of 117 files at r1.
> *[Reviewable](http://localhost:8080/reviews/Hyperion-Web/Nebula/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Pull request merged**
